plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

def mcVer = project.findProperty("mcVer")
def versionProps = new Properties()

if (mcVer != null) {
    def versionPropsFile = file("versions/${mcVer}/gradle.properties")
    if (versionPropsFile.exists()) {
        versionPropsFile.withInputStream { versionProps.load(it) }
    } else {
        throw new GradleException("versions/${mcVer}/gradle.properties not found!")
    }
} else {
    def rootPropsFile = file("gradle.properties")
    if (rootPropsFile.exists()) {
        rootPropsFile.withInputStream { versionProps.load(it) }
    } else {
        throw new GradleException("Root gradle.properties not found!")
    }
}

versionProps.each { key, value -> project.ext[key.toString()] = value.toString() }

project.version = project.mod_version
project.group = project.maven_group

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property("version", project.version)
    inputs.property("minecraft_version", project.ext.minecraft_version)
    inputs.property("loader_version", project.ext.loader_version)

    filesMatching("fabric.mod.json") {
        expand(version: project.version,
                minecraft_version: project.ext.minecraft_version,
                loader_version: project.ext.loader_version)
    }
}

def targetJavaVersion = 25

tasks.withType(JavaCompile).configureEach {
    it.options.release = targetJavaVersion
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(targetJavaVersion)
    targetCompatibility = JavaVersion.toVersion(targetJavaVersion)
}

jar {
    def projectName = project.findProperty("archives_base_name") ?: project.name
    inputs.property "projectName", projectName

    archiveFileName = "${projectName}-fabric-${project.mod_version}+mc${project.minecraft_version}.jar"

    from("LICENSE") {
        rename { "${it}_${projectName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.findProperty("archives_base_name") ?: project.name
            from components.java
        }
    }
}