name: Build Multiple Versions
on:
  pull_request:
    paths:
      - 'versions/**/gradle.properties'
  push:
    paths:
      - 'versions/**/gradle.properties'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Find all gradle.properties files in version folders
        id: find_versions
        run: |
          version_folders=$(find versions/* -name "gradle.properties")
          echo "Found version folders: $version_folders"
          echo "::set-output name=version_folders::$version_folders"

      - name: Build and Upload Artifacts
        run: |
          for version_folder in ${{ steps.find_versions.outputs.version_folders }}; do
            version=$(grep -oP '(?<=^version=).*' $version_folder)
            if [ -z "$version" ]; then
              echo "Version not found in $version_folder"
              continue
            fi
            echo "Building version: $version"
            cd $version_folder/..
            ./gradlew build
            path="build/libs/*"
            artifact_name="fullbrightnesstoggle-v$version"
            echo "Uploading artifact: $artifact_name"
            gh actions upload-artifact --name "$artifact_name" --path "$path"
          done