name: Build Multiple Versions

on:
  pull_request:
    paths:
      - '.github/**'
      - 'src/**'
      - 'versions/**/gradle.properties'
      - 'gradle.properties'
      - 'build.gradle'
  push:
    paths:
      - '.github/**'
      - 'src/**'
      - 'versions/**/gradle.properties'
      - 'gradle.properties'
      - 'build.gradle'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Find gradle.properties files
        id: find_versions
        run: |
          if [ -d "versions" ]; then
            version_files=$(find versions/* -name "gradle.properties" || true)
            if [ -z "$version_files" ]; then
              if [ -f "gradle.properties" ]; then
                version_files="gradle.properties"
              else
                exit 1
              fi
            fi
          else
            if [ -f "gradle.properties" ]; then
              version_files="gradle.properties"
            else
              exit 1
            fi
          fi
          version_files=$(echo "$version_files" | tr '\n' ' ')
          echo "version_files=$version_files" >> $GITHUB_OUTPUT

      - name: Build and Upload Each Version
        run: |
          for version_file in ${{ steps.find_versions.outputs.version_files }}; do
            mc_version=$(grep '^minecraft_version=' "$version_file" | cut -d '=' -f2 | tr -d ' ')
            if [ -z "$mc_version" ]; then
              continue
            fi
            tmp_props="build/tmp_gradle_$mc_version.properties"
            mkdir -p build
            cp gradle.properties "$tmp_props"
            cat "$version_file" >> "$tmp_props"
            ./gradlew -Dorg.gradle.project.gradleUserHomeDir="$HOME/.gradle" -p . -PgradlePropertiesFile="$tmp_props" build || exit 1
            echo "LAST_MC_VERSION=$mc_version" >> $GITHUB_ENV
          done

      - name: Upload Built JARs
        uses: actions/upload-artifact@v4
        with:
          name: fullbrightnesstoggle-mc${{ env.LAST_MC_VERSION }}
          path: build/libs/*.jar
          if-no-files-found: error