name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build all versions
        run: |
          echo "Scanning version directories..."
          ROOT_PROPS="gradle.properties"

          cp "$ROOT_PROPS" "$ROOT_PROPS.bak"

          for version_dir in versions/*; do
            if [ -d "$version_dir" ] && [ -f "$version_dir/gradle.properties" ]; then
              echo "Version found: $version_dir"
              echo "Merging gradle.properties..."

              cat "$ROOT_PROPS.bak" > "$ROOT_PROPS"
              echo "" >> "$ROOT_PROPS"
              cat "$version_dir/gradle.properties" >> "$ROOT_PROPS"

              echo "Starting build for: $version_dir"
              ./gradlew clean build --no-daemon

              echo "Build completed for: $version_dir"
              echo ""
            fi
          done

          mv "$ROOT_PROPS.bak" "$ROOT_PROPS"

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FullBrightnessToggle-Builds
          path: build/libs/